apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-service-home-assistant
  namespace: external-service
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: external-service
      version: 15.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    portal:
      open:
        enabled: false
    service:
      main:
        enabled: true
        externalIP: ${EXTERNAL_SVC_HOME_ASSISTANT_IP}
        ports:
          main:
            enabled: true
            port: 8123
            protocol: http
        type: ExternalIP
    ingress:
      main:
        enabled: true
        hosts:
          - host: assistant.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
