apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
  namespace: calibre
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre
      version: 15.2.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: calibre
  values:
    TZ: Europe/Prague
    credentials:
      backup:
        name: backup
        type: s3
        url: ${BACKUP_S3_URL}
        bucket: ${BACKUP_S3_BUCKET}
        accessKey: ${BACKUP_S3_ACCESS_KEY}
        secretKey: ${BACKUP_S3_SECRET_KEY}
        encrKey: ${BACKUP_S3_ENCRYPTION_KEY}
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backup
            dest:
              enabled: true
            name: config
            src:
              enabled: true
            type: restic
      media:
        enabled: true
        mountPath: /media
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/tholos/media
