---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: freenas-nfs-csi
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: org.democratic-csi.nfs
deletionPolicy: Delete
parameters:
  detachedSnapshots: "true"
