apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: calibre-web
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre-web
      version: 19.0.13
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: calibre-web
  values:
    TZ: Europe/Prague
    credentials:
      backup:
        name: backup
        type: s3
        url: ${S3_URL_MINIO}
        bucket: ${S3_BUCKET}
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
        encrKey: ${S3_ENCRYPTION_KEY}
    ingress:
      main:
        enabled: true
        hosts:
          - host: calibre.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: auth
                namespace: traefik
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - credentials: backup
            dest:
              enabled: true
            name: config
            src:
              enabled: true
            type: restic
      media:
        enabled: true
        mountPath: /media
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/tholos/media
