apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/8O5uGm1PvOqflz9zGOT8mMlBRaCPIjhtaF+tyk8JyhIA4jCGqCZ+UOqMnrbyZehsopSa2WfPuxw/ZQ5o1GRnTheTTknastr+YIB4SRe5ufkqcRs0rgFfaCgKrliBcbL9rkmkO52woU/JZ8ctBkV6LpJ5ddxld1ifqU5cSi3nXV+NomLJoilsHvWhS1UBnT4NM1TTSrIn97w2MK8APf6w/bAoM8pvYoKsRjiBVbrmRy1RIoXr7DqP6dV0XbuGFfRYMdwoes+ng1IlILXksoeY9B17d2EhaepU2pSA6iPKoDlC7DlgpZFhnHexYMk6boKfu2q0NI70YaWBN/AtWqFpne6GX4XiSsS5H4S7BoH7PWAfcJRECZTfsYHNZ5sa+mt,iv:iUCE30U9xEmLPufHfyNwu/ZzlqOo3i95y/95Ugdwo2g=,tag:03GCeMJIf5AMFg2ybOqp9g==,type:str]
    identity.pub: ENC[AES256_GCM,data:B5EiLRwwOxCG0qLg42S6EaI82g6dc3WTNx9+yW0BqX/juyi9+dAouzO7FYI51F0c85kFVQDBhBM7wt64LACsol9YcHm2DjbkLwa2OnTkcOQhRdMtcq43b2TSd6SMArAPLQFZItTcOWdjgdSlgpN46mI7gncyf4RszS06iMqPz8yAXjZrjS99PbFJ4ANu1luyh6LynbvAv9dsZe4od9I1qdnzrseiiYIbDudBx9hvNQTS9NsMVCDDy46Dndr5Vc83AQ0U+14qTCsOLUKv3A==,iv:oR3YdOUvZYgkiSlIz02b0kNm7kjkjwNIp/srECN6qnk=,tag:NqWqTn0iA1W5K+Bpi3xZ5A==,type:str]
    known_hosts: ENC[AES256_GCM,data:OgdvkZ0iJduaLKEsjOUZLJiGXQhV7rrbq0WayFpgh+3MCx0sPXyexEDEGfPxMOfHXmbjjidnx8awDOnLbagBsRSRbG/VJk0fq6aPCmO70O3zyEfZccD5Z93ckOM62YxXFqTkj+cf0/uk0Z35t/ZtNVBGMxxLye4lYJ0qInsIhqUDzRlKRHSzuBiRPV09Mi7S1S7uNV8W3S0m05gcWthqA9bhzLPHtNtc/tuH,iv:O1zhyaZ8GZsXWsU2SeWw8KKVupZrcQWVr6tNb7IQmDQ=,tag:PAwFQfwbZYnJbypa4jTtfg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UXoxV2N6TVNnbFhIbVNY
            QlFGNjVXbEZ1bll6dmY2WVRRbittSzMvM24wCjhUeUdVRStIZUsvdjUxbDZLZjZt
            VDF1bkhKczJ4SjNoMFFmQmRseGZTMDQKLS0tIFBiZ2ErMjZ3YjNJRlVIV3ltd3Z5
            c0I4dmNkVjFZS1FRQmx5a3YveXVtVHMK04wCSw31F8eUKLcgHjlBRGK4+b2odIXY
            bHygDMBej2njfaeVO+viy3fShwu0KtmGqIYhRrkCRGsMguw74cPkFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-26T09:39:00Z"
    mac: ENC[AES256_GCM,data:rKCzo10W2sbfwR8ev9QOmVjf36n69DwRQEzTKYgUioX4botOZkJTyP4VQlss0AkoIb3NGpB3c5QTSkc8XLwQcX/jLJakzWCSFsvSoDxrXygz4EDGbYSlD/jqODngfrRD2KL/HY/7qKBr67pP6Bpb3gtR+FwhJfBFqVzquYJPTkM=,iv:wjNEUseDKO/l+btREryc1837dS4ChGK1VUS1y98B5kE=,tag:NbvAF6v2qwcv4KjZjAjZpg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
