apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Qr9hFE1TBwkUgamQfD/Bfr4G7nM2rxhE5HqDDvLaF146KZmUqe/i1r6SZYiaO8VQflqf7oOy3rscYUmM5BHmcLZb1OWTKwyXcKFT3TFJ+rMC9aNDiCmk9nUro7m3BpFp4t3FRfYkiLAnUx90NFIpfR4N6KGdH+nEtYxk88PPC3CpEzsplqb5ezxbOyroOuN2CbDWvNGIvrdOaq+fajbP76wvSwpDfBkLXWgkC6DZAaqHfksG4oLQw+blu5sdwUhiVBlAI7U2pexeajXpjIsqfgftchbh0Jp83Oj5BZiygWygEGGWLdnT5RQIqIR84G9pXzI6hZhiwcbFeuyHpzV81M7PtYSPV5eIkhcQDVXxil0JZrD/YhC0mg8xzSFMxiTy,iv:0s5QRH06FUT6S+S6YQ80G400J4eu2tBx4ZHlbu0tDNI=,tag:pr2jb11s8sBHv13V/w/MyQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:us8a5EYQMiJlk0qq7e9eTNqdRlI4lWKDdqH+G/c6fKl6c09OfitIS4vRLvS62a9VnQI7e9/vwYkZPYG1IWiijgJ2iYEcU54Li7Hbi3tB44GEro0qWJMt/kj93k/s0J924qLwoFSAjdsCChB0E1WjjQDF/XkkAILko1oF+91C4I8WBZ1cQ4DGczzgB5C88czikBiISprDjE6xuNajZBkovL997f5+63GRndSeAik9ZxYmOC/boghNV85W0UNq19H+wPpgwcX6NIaSzT2gTg==,iv:Y4qeTDUKwVTd22Isnw+n3iS4STDSwHI6+sxqrdEJJgs=,tag:c1OUxvq4/5n1E5fg4GKKrg==,type:str]
    known_hosts: ENC[AES256_GCM,data:xQ6VeIiIyI59rYzXPmAv0j4exZ6EfLDwsy6Hpma2DeNeoyvtAsm5EUcbMEcLFS4YHMRJ/AxjWcJgprbMuK+xfb2JOrYqn4Q89mhLNVTS0xYykGEyLKJjQ5xF8x+Z3Z6JIW8N7f9x7YWXwHQZS+piYOvWbnFgdAWW7lK318nQ4RiEs8tT6WvkTTo2lEO0TdR9AG4l1xkyTfZ6ziPdLTY6dd69JyKbLLA9wM24,iv:ZRQhgtQm5st3lKP9u/PXQl6XksaboOPMTbD6QDq0ViE=,tag:jxh0BmFk3bDRvXQKHT6C7w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdm1kQ3FEdmtScTgwNGo5
            aXhZdmx0bStzVjFpcGtqaVd0S0FMUStEWHpZCllyQWVQRDNMQnRxNjlpQ1k4dERP
            a1BvWldUVkRYOVRCeFhGbU5FSys3VTAKLS0tIG90NndsNlVuNUpxenU3MVB5OUlq
            aDgxc0FTY0k1aDN4RDRNa0grampJRkkKmS4GTvVui8fz9lIOSsktwnfDQgVRjSrg
            ke9lnmROa9JvNnZGze0czEk1AowKgwHeTBNs/Dp0Vy/St7BjIYp8pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T15:47:40Z"
    mac: ENC[AES256_GCM,data:qSAWzAZes5fU+lAOhhB2FqU1NIZ/7evOIgM+O/bGQBeCPXA4nb3CHLe+ZNNw9ezHcekJfpqwcifXombVfK71L1TKweq/4cKN6j6hTxlT/jtSa96TwAEXc4zhgfyDB0wTc4h+1/4IgXrr7p5uXuEGUNqZfPOwhNOxRXJYEuWs8yQ=,iv:ch/+4Bs3E6FnvgE6lQus5AX1D/anehoRUao9YDovT6A=,tag:f3iHuADhlEN9vkVtZHjwAA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
