apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DcGMvaMnnxBhvJ54jsCWp+78+kR1Nm5NO2g88ZY/icjV6Nuh/IdeXU+ESXUBn2VJqziml9X98Pw+0ORsNyl/35LlceHKybcdBrviRvPdVlRtdLtrjtvJKmj0RxkVNX88xKRZRGDg/D6sjoRHU67BEEOZrAGFjejPokrQYlTuJQU5ctBesmYRxpT9LoDVQcOSTJU8RpkjeIC/9h9ako5kUHNy6n6VmZf+wEF/YDggYupyA++UKG3eiw//SlJPj9MpsuHw0LF1Hg9msNhCnievPwdOMd0ZXJ1ksCoKk9SX17MNCgePTVt/A0ehKWJW9yY7w4kJeUADFVA3TfCgQfEIee+OvQYMKA95lYBi9sO3YiHdgmgvG6i7dW1uUJl2z5IX,iv:TNi9+6O2EtB90lI1hmj/J8lq12j2zJywoiVQK0jUkbY=,tag:KO7q3vNu6/RQZnpzWr0bGA==,type:str]
    identity.pub: ENC[AES256_GCM,data:y5gZTrRMCZxKdkxrc4yoUUC+vMGZE0nWFArIZNYzfRK3QsV9RLPD4dHx0IVAB7y0j3yLDE74t/gSztXwXNpmCw2rjjkEyaoESXxXVB5nMj8TeeFea8favrbvLe4X96QDUAE/DBAkJVnqm0TG/isGq3M3L0wk6HYTRzAPByNT0rK0vcjsDhrLP5K74sW9b5MrMnN9XDkgbthJg7aWPDXlw10ydjkcDlzjHrRsWbpzd3a4VpYNRKHMgxSitmdBsNpnZrzx4cKAguCA6EUmRQ==,iv:3MKRiFBu0iscdXqF58/kcgFLjCrlsGn37sWuz9AK4R0=,tag:yVgC8U2QwKKbR4rUTzTwXg==,type:str]
    known_hosts: ENC[AES256_GCM,data:sL865wB5mRXws9RHur9cO5nNR+6dK4IMUZmunHLsxitmxoiq44zU0HHiWQs2qMwcxdjFqJmhmCM56niyrhGaBZ68hZXrTd9dfLXuAHSDx74S5w7Lm5kvPls3TEieeLdhyaEOIhYIUbUb5nJP+b2F5M4cuIhmppBRLoMXiB3MkKKelEukrQEK963Mun4NV3BzVCrbUppwhCM0fX8HNhhGVhAWjJbVoYzlBChF,iv:MmRX8kA/aGciLdMyypXSVjQXr0W2+qZKUEOtHzOtqKE=,tag:5F6SfNhaLXuGdNJDu43urg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbEt1SXQ2d3BqMkYxNCs1
            U2VadXJuS1g4OGJ5aEtGb1JMSEw1aWQ4cFIwCjhnRnRGNWF4dFNpSnlkT2pVZWd3
            NTVpUjl4cUx3NVhjZkRGNzkrQVZLb2MKLS0tIHBoTlo3OU9VRVQ3NUhCL1UyYnpR
            aFpIZEIzTm80MlAwTGRoQm1HbXUyTWcKyY3MOpR6GV10Nu9pkWbe1elKNr3xxduH
            5wcdZEUKfXp4coE/UjVlF5KaQZ2usyMP76NKiEw8is+PiiY2+hYAPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-28T07:46:14Z"
    mac: ENC[AES256_GCM,data:Tmd6LbrugTRM1V528uFnW0gy/buSALBuenPEyunixPbU0a/dwji3+C+SVxim3nFqxbJEClLund5iDi/KnjU4YtpMQuIZu6PUJnU7pDNByIcf3/iP6vXilA7mJ3uN6HJ0VPD16cqXpwFLVdHqeqhRmEq0N5Nc9iI/b9LCvHBQyYs=,iv:0Ye0biUOq/qACIgtFIOb04RX1XovV4Rmn0U1ieq3vOQ=,tag:6icI+wyJq1GhJtYLjrt7/A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
