apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:epW85rKw9dwQASW7mLY882PBmkj5DC5oBcX6fWZPJlW6AgcGr0NXWv3HiTMwIqWsWFgv28vGGaaCa+fG0aaixQxpaPdJ9FjIxvLGUpBH56VzvTAazERfll5WFFboUUFKuUMRZ72YWssD6LugZPkdynhHkJ2v/4CAFpiGBEhw1fve5td2F5U7jqCmY9b563CraBUv9Gmx4CNr4ERxRMgafLiG4gR1CDGO2JtwbBK22sAIA53zqeiMg4HvEzf1IGFjDmHYOhvnRCQHGt2RXfcJ4ZDd9QNsqawrhC4yeulZokMnhUJ+6APEiKK62s0CBxYjDW9GGfyq2W0tuK8teHuho2mNbShM6bdHFmkNex7bgHBW6fyBzDYi8zeXJTiUEYxy,iv:gHxg8pEN23Gs9mbMRdgeMXQA3jQdtVufWg78c6LDREE=,tag:ahxWnxRv4G5mUmkxeUTC8g==,type:str]
    identity.pub: ENC[AES256_GCM,data:ErA3CNHewy7j4lF7vxgtdWfPAE3qrXmA3OLhaWLcp0CJJSBldW9c0KprCK5352l3GdywCsR0j837xlNOs0ILCKOznQYhE/8CZrFq7U40mv74WQJ3H60kYgJuituKOlTTTwBopImRUxDGw1qrgDYlsGQO5rdWjUThyWoCj3q3BuoYxLxYAN5r8ouhLOz4EX0TauxKhkneU6BaXYOaBdeLFuyFwWpkxskDyyjErr+uQEUD1EzIZYm352Dkju7u3HVnDd6rxsahOSpBbORWUw==,iv:XgIZZjiYNiFayGzOePyydjithbQH4xc1txbpCQ6LvGY=,tag:I6x43TbCBNsesR8ew/9Zng==,type:str]
    known_hosts: ENC[AES256_GCM,data:X9/+/A4pJuS/tAslRZapLMC9gEKgPjaGE9aQWuiqEt1gy7j82yU7IzVBB17Qd3WaFcc3/byQTb3P0T4JGoJvf+dxAQxTqD70IIaSeFl2OgzLLnSHEEz3FjobppBKk59E03RVceIk9Yneflpy1wgoDm9xPDJ5i+45L1Ux+ecGCCKJGHWUh+AcDOLAoF62/6lNWYF8GmmgfeSVjBBY0ELJEmfu+GOK13c+t9WR,iv:YCKaVASzYWGFsSicOtr7q8xmxjIxBBHV/a6Q2WkercU=,tag:RBNJtHpDtZU7fy4zWOLwOA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZGVZdDZPV0pONnpBb1Zk
            V3ExenRoemFDclhuNTRZc0l1aVRoVDNCd0ZvCisvNTRVYjl1YzRsUGVOSGdIekxl
            cDdKTDNYL3A2NStwQlh3VVpvN3dza1kKLS0tIGF3WFV5Y3FwSlpjcVlqRnhQWGpB
            OHpmbVpWTkNwWUNMTUVRYnhBQmVQRm8KThzGRLCw/7nx2BRhdHng56n/DkP8xxos
            dQjVDDuI2bQt5yUSK81G/u5i3Zqs3DgvpwgBZEop64/muA898X816Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-04T14:19:04Z"
    mac: ENC[AES256_GCM,data:0xMP0te4DaR4JHAgdyOTKInxq7Qx/EvtwXo3Alaih03wBiXLzFBdCfyBlTSIO4DoFcjXTmjrC5h/Zp3tZNP6hPIGxdBPpVZZjn+F3VzBDljBIMzUpT4isGzQVT6DIkIEMuWO/QL++OqT0eZLfdQg353MBymkn6gfDtb/yXHIpKg=,iv:D/Rk7M/jTHKkRc2ZumEbwaofFLQinqvT6QxppmFXMTw=,tag:tOMc/bx+V8TlLK+QtFy09g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
