apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OQBU2JJrOs3gdIs8/ebp2OO5MzGH6A6pv6nlKdXIaxonGzl6zBO+MEa0L6Q2m1vdov+YPYn3+qQjjq97P2/Sd7YgAtaaooc/8IL/Riok07Gl7XyOVZQjAihkpZAVNDxh5e1K41+IxgFMLteEps56vD+bZEulW5t6h6roBHYn3ghkrN2Nb9e38AGlCRU+j+lx8+oY/xRFPAhBJ5UxsNi/nJO1K+4o5/M2Pa7sVsuzezPT9s8+a5sWgQ0We3DnhwsJ+4B/s2JxChjJGYK9pAUPPNxImzrHvJ9HaDgBeRM1Ewvy6iyvW+8hnRXuUj6I3xNbsb3Zi9izFIQDegPPszoStLfkcYeXKO6WbYlm+pPWdAHFZCeKomwnWYb1oZHGAd0Y,iv:9ldMoW1pmsF2C6uJ747VuGzzCh8bJV5jW8EXvIyfnZ8=,tag:0p/I0BuvGmsMNZbg3+1bIQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:oaX0Pp7QmARxhtqS+D8lk920kC9uJZv1SOcXJ751+AAaj8p/MJsRGf3MzhGk4SsjtCKHb4KYh3viboPLZ+CPG1Ie1LbX8A4hmExqmh2NgN1lCTkUE6qUT5pO/4BbJQq+oxb3uSdSKyGBxX+E5JPuM+B8foqRjfhSNaTtke2GkwzE2+hA5drwdonL+zRpZzadOObMAE/pr9JFXp6KzbfMOa+Tn7tTrj0WZYK3nAcvDep3M0Qz0ME/J109y4RukzwZyc3v+PJnHBriqlV6KQ==,iv:qHjLpLChhQT84LMLVfQr/b5UfxRgNK/w+5xe7boTkvM=,tag:jgiLY6+Mij/ZwYjsfSyBmQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:NIealUxlVUqNG5OGVhSziidC2L97PO1uVPDmDKgWdgk5fJrh5GpPLWL+wu8sUJFIRLAvg44Qohx4doTliNI/UvhJrUB4XPfWyYHuDi4GnynZ5IlHWGoQSTNOEV/vAvKG37hPwRm4diWkRyX2Laz3Vw+V69jfuFPULrU542E9JTtqvDYuFdWSmJOHuWVPhGST2XnnQocmJPlcavvtdYsHNOMHbHQ+Fr5m+oXh,iv:p05nOVhBX43x1YGnKMbvbawhovj/jA5G8avwzJFCIw4=,tag:vTpIul19G0hYa5qpO83ZPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka29QcStYOVhLVk5sUXVk
            WjR2WDRTTEJ5TmViQXpYYm13OTFNS2Myd1dzCkdWckYrY1BlRHUweWtKbzBnUVRF
            TEZENHhTcUxJdVFpblFhNnVjWnlpbmsKLS0tIDNUSG52QnRNV1hHNnEwbWlESjBh
            ZE55RnJOTWsrejYrcUxJNzBKOUZNblUKZV5Qzq3HBrSW1Ea/x3QphpEcIZmZAZdJ
            MQu9WE6FTcS2gWKQlLp5d/n6A8jG+qhQD6blxEhxVDrDB/jYSt/BTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-13T14:05:21Z"
    mac: ENC[AES256_GCM,data:nP7WkqUAKb9x2q1QjQdhdJS7o/F34SZOIOJDZMNm8ebZF4pTRRw6Dn/gmciddlwMwj3xlTPMzeCewpQA6b0BiaKQX+6Ex32l7z7UK+AmD+NWfjRr6zxJ4iH6avYRlTk+CjQhZNkTdmjYzScegh7/Me4f3WjArQPjC4CTn8YTlqM=,iv:UMrA8ZuQA93hG1rQOtGLYseoVSt3ZBOpBjWOF+01vDY=,tag:RoqThZ/Y6KIJ0OIXxekPUg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
