apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1sCBUoL+AlYWCJufuRzqSP2ULfScrjPqhLTbulX7ipuqijSW+Bdr+h9L6/H4wIbWsm1r8FHJoctAI/Yn7dnRQ7lus8MMwEBQsRt5e5BTlKL5M+kBA22DkSA5IPBLOwYeegDZQeRkyq6CiPMA34V4VQHnhqQ+TaCOGSOkMfu8xfZl2lgfoUaIx9IQexstnbrZHz/YgcSkgu786vyUTZ19IFbFEZR37cre810ki7E6Za3oSwDGh+z63nyrjfpu2o2+UcJV95GQD0pfS/KpjtY2Ir8u7CXHseiRvWaaNqEjcN/mt0lQte1h2EvjGpDazjo1KO1a1CdcNAH2TOYJybT+9HTuLI+k/AdpvDLQov2aXNHRNPgv2asexJjTemB3cNJY,iv:dUnJl0j5NaFT0hK7ERBBPl2JAcRSb7OhQhEmUPPPwm4=,tag:d3VFYHi7grMOoSvzFhzMZQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Phe+Yhuc+5+B1P5yab/EtJqn/VIdUguijSsabDcwQlGQ9z09txruLGJA5mw6QacT0MI2y1QqW0nGbzBSwnfb6Sk77eLJE3i/as9DNEjKPf2FMTE035EYqyf7iWLhBeRjexfjOdMVwga73bQPTgBRRvVS1f9sdCPtVqJVDce7cGb/lhJ7vWo7557JvGbLRPtH7Dh8gEu9SSDSHu5EzAJkjkfTHn5Yt+gylUSqnUpvzC16B2tvft8/5gTFB+jLCdxrT2/b0nsHFQh7XWjbiw==,iv:QBT8MWkZumjSKkhitrYBWibOea5D+OvcdTInwSD9SH4=,tag:2yPsZd/f6sC+nfqMl8i5eA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Z3HlB+nNkougEyVqq+3fB1gWe8anCTdiMHhxnz4w3mhoS59YiTUrKfp2Mt7lSL1QYTVU9H5V5MtUVZgjg5+eSK3dOpg7Le0todUvXBYN6yz4w6tGp1V30FGy2KMIFXkEJSQ+M4fIpMGb3SY/do/j7BNFJpeFoETytkAglzwhjeesMAINQBp2T/OYDE91PxDnVRE9FOMARyc7uQaNsWmnI3iefrV8g6C6/JfF,iv:0+mCXAnMQXos0KscIDnbSDouiTkQly/JEFbc57Mr3GU=,tag:OyuKjlIdZjli+t9+Jia9iw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZjAwRnd6RXJyZHovYzZz
            dHpMdG80UndXc2ppZ3hUSzdKVkZNREt3bndRCjNlOWZTWUtJSU9xY3l3dVJBR2Fx
            TTVYUUg0ZU5xdnZGV1cyNXBzOXd2MG8KLS0tIFl5L0FLVWdHNUMyL2dLT1RmQjlW
            c0h6aUMyUnhhK3puMVNCc1hsaVV5OFEKcNRvMfOvWxwLXSHsl+jeFXMWhX7nhdju
            d763sDi1ZLiJ/JPX+RO4ZTNtviAoVC3CclFhNrTCqElWS8aGRMqQUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T14:03:45Z"
    mac: ENC[AES256_GCM,data:GS/PBLtAwTIpLWqmDIY5MGXBL0IG2SV4pH0qBbO54Wr1hvVkhJ8waUVAWMKtQogWauet7CJl33jjbfmERlEcIsqbfsaFLTrfa6vj5mrhHqHs6TB0m58jRtiS061+NFZ+b+kIjVGx/m0x4skLyg6waV6XUVwcYo/5LrXzmqFSuoA=,iv:hNb0oI494/0oad2Hou4oq6uFNAJoWJbZUg7IkYjoR60=,tag:SDoHM46VzjnYPD5+JwzhoQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
