apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HqaP6/d6feRK33LeEqWcRSQHuA+lowwlfe41zY4bIHI5Om4sJfk3SQ9KSD8Cxfoskc5mmzK+SYmiy2ckZsY8v9RHF4GoaSAdE/Yvew2ni7tW0YBh5TqIC5p2ZHq2h78+uthAguqnuIfAaGPDizZatWh4R9uBQlk0ZAicdSVecKZ+sPijBcEAz9vTQ47Vx03daPjQQzqx1s+olsrTstRkTg3b/jq7eYY91PrjNPmaxdKVznCanErN99TgCgBI1iTcaFS9m7njAeKgx79KkAkg0o06fFmHi8zOC3hos4ImoURsWo0vb22ivIpA3JISaRqxXXKzHNoWjQuFwQJL9TjKVuoM96tPF6VIp5Zo8xErQeJ3ehRxBwQN5YfB0KhpsjJh,iv:K7uWWDx20Ha4PJOiXeRZQ3Dk0r1ygeGY5m/afOmXEdM=,tag:yKjFeapPK1Klu7HbkdGg7A==,type:str]
    identity.pub: ENC[AES256_GCM,data:fZ1Kb/y6vs8/13zcDa0eySm9AYR3QrKnGMG0T7lY+Oi+610gk8xWhCsVJsSFpk7AL53tzrWoIyA89REYbg9Wz2dxTeAPqAYvaOMxKiMIHU9d32kkkwvp/rqzWxJa5bLrfMEWXZsAnA8xk4o1zpSTndNN7Goz4y2ZpHkwu2PCogH3UxnUkEOQTOBTATjObGnYidvi/0uwbnJtNi7bQ9st3W9DgQvWl8+kszIEJmQZd7pAVk5vJiI2d7rSfPVDPRPRgcS/4y88g/eYYQrBqw==,iv:bQJ/yAnhVLxxDSs04f5VPVtlyB2MJ3EDn9ZOF1SBVyI=,tag:3sIlvH33Eso5qQjNeJ7+vw==,type:str]
    known_hosts: ENC[AES256_GCM,data:mfM3UYOT3Z5ZBVSivhxvD3OXf/7emLesJ4iDNK52IYXKyY3bEck6VOiwcxUT8XVL9dZ9gCrpOpkzQ0UNwlFWxBAsUJ1Q5zFnX/nJRemPBr3gMs5NNMQUbwF953dgkqmtIU6XJQ3OfZ6YNvU+6Yz1f7Ay6WNcMBmYEGIOqNlpJuJ31jhEZ6mkUKqHdsMYLF8b9drmOrLGux1ZIIyir/wu1xs9s9Iob+911XZm,iv:ehHWmcSC1h50m8ahwEfycS1/If49ME/6NtVpMdXkW3Y=,tag:t/UBad0Zz30lKXedcmiyiw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUzFQMGNLNG01RUtweGJo
            NDV6RGRGdWxRbHhsQWZaKzI3ems5bC8xMXlvCkVjSnExSHRiemxtMXpnaU1vc3l3
            YUpUYjVJYit5M3ZTUGVaMmlFbTNRUUkKLS0tICtwUCtQSUxzMHk5MVpmdUQxbm1h
            R3NaRjAvbUdpdUZpU2tCR3BOSzR2MTAKRi5gpicHSYPCMmidGnd9QHxVKVE8gYVu
            QOkDQP8Wac9xoaHcHhQUN1H5uvD6csu4NTn3YXkZ/Ny2yqZx/W6QYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-04T10:24:45Z"
    mac: ENC[AES256_GCM,data:SCupn7stWxtaE17AT1ujPWeKmfWrG2nc+1EO3N1eQFi+zyQAs/1bL8n6dUGTLT4Lsb1GeSboTc4fTmwfYNQvTTH/TMqE8RL/rJ+51K5uA7LMHuu5Xd0+n7s9p5RG5k/Qj5jDYokpcEzrBUue62IwcePbLfGYGsE2APFCD36Ty24=,iv:EcBoyCz0U7TDCqMLn1NlfhKTbLBmUrPpWJgX4djdngY=,tag:uooYZXwlkKoJw4QtX2nv3w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
