apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/l0YUnMZzooqSLzk1WCdvePcofos6E2GtzO+f06hb6v2ZPuuvXXQJI+BF6LHi5LHDKo0ObHlkA9tkT7u4t3b2JooHs7PykCUk6nQNQCDT51JZEAcanIh922qc6iGcB04guLsgXzPSQn2/vLoW6s9bc9NZJYPvuZjxTbK5Dsk+BVRSIVV9dbmWMmySGcUUqMdr7HREeoHeZ+tW2VTOa+8rKvOPM3T1Jq1zEjZmEqwbad4KZov4SdbefA0DxlLX/LE0Te+Uphz48chPU23NH+gwX2wud0kpMiT/xYnsDbke7tj0nSZg2kaf/TVDT+yuRgjrR94hXQfPTk14cHzVedRQDpT7v7qoLlQ271nP5RF1aHoaJ4GmcMIbPWprfetVGXQ,iv:kLFp7rtY76azs/HC1kqB0R5qtaTSyCG8ZDuqEMS2J8E=,tag:r8Kng2yjySEDzoKCDHaO9Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:3lxkfbfr5ABLAhigW2/Hs7/OAbGW4IKNd8VsAitwtmXhz9AZPheu3gSaTpS6C7SIo73NdBtPTRoB0nws+SdQ4XlSOmN8TAoPK1SDgGWRvy8O/aLmwOcifehiPTBURwwOcyx4QKGolGU/tEG88io9uNwgnhnMwHyXZblRaTmMzVpXI7UXpMzyAq0VpLnm666Uea485HJ/2JYJBW8XRcegTKCXYcxEhFk3QXXeEKYIU59ETkbgxK79lYhcxoNj8oUm89wMi8F1cDk2Sj+uwQ==,iv:/qyGRjMwJQLlpCs1m/YM28zzIQ7L5FUg3VhEvGdSzUo=,tag:pFogz1HDoefh1UaTU0j1rA==,type:str]
    known_hosts: ENC[AES256_GCM,data:3fE6TMtj3G2lw6g86udt/lmhCM0E3JMWUtPEj0FicgbfkIY9JCUO9KWldUofAs1q0eJCAj1V76lfVscxKCvM1QRe2y4GwJ79SeAMCU5U6ZnFMKE2r9g8A/cNIuCq3fb0Dg8zqnfTONHK+pZk8RffOYcWNpeXba7iJGIMGJxGZOpPFIBFkZ5Sa935QmyhKUUQiNByIoVI8pmDqMNG5xQcOJ8Abjo/XsdjCAXT,iv:5JWJiTtaESpmVUMoJPDWlGvPm34cCXCznAFq9yWSzzQ=,tag:KRTINw7qaiGOglXqqAJMbw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNko5RWxldXlwVVRRZTRW
            VlVxZ1pkaHZaSi82ODR1MFJIcVdnOTVnM3dNCncxUndFWDRZaXRBQ0FyTGNKRGl6
            b00zRmNVUUpmb2xyeVlIS2ZBci9kSEUKLS0tIEFEVHJOSUN6OTBBMGp3YlY5K3Jm
            V09Rb1dPZWJBNXhjbDJRMUNFTXZOajQKf/3Ib6DWf+y4p8wnrpCpxK3eS3rlZdSE
            ceKV9IRWSlLdIPr3cx9KJsoEA/Xsk/F+vjkfsjWUjxJvq7yi40W8VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T21:49:45Z"
    mac: ENC[AES256_GCM,data:FtE7T7yFcqd9gqDebDv8xuzZVCm1cHtbufWAra7FfD0rgcRY1aPd+jn7myGmYV0iNghGBHnU7re2bS0nVWMuTv+Ap5ehLl7BI4x53vUp2W84rjkm+324ciRqTg0LSuO6NHF0lOUIeCNmpljVk0AVMHbh2KuzEA69pmTmHb3sLZM=,iv:Ls0fKq74G5RA+70q+RjB561OALM7Bnvsr3b/g44/Vek=,tag:EjKlgQUIE5p1W5CukshE2g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
