apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uQp9xTEHVVeHEr0hY/SWvTXWxunnSR2cLx/QCe4CyCJDhMZHd1MCH8hNqoyBllXNeDasQKTYzh8tx0mHx1CdMvUZvIsQSp/TX8GGkORTUIgug9kVha4Vb11IzOktuW0GM2/dhKbsF34ak1Nvog+sUdVutukaXM17q1lgYiVP46Jlvbi7PTKma4ftE6zOgzJ4ZScRIr1BBZa1PJr4dNR4PN0J55ArNkicH/EkEOgCADDGKRJfEXe6vAFmTviY3X8mh13F8nR0D4lYHbAmi2UFUPUojO0v0TS91CyFQ2RoiZk7CN0hUwdf720/lKDzr9vg6Ypfzf4L9BCrgxXNruYd6UlT7wtkjcrNuW8QDd2vt22SS1n+QnIgByKvLdBOPj2m,iv:qWnPUQjILHvp/QxOZlw8QvQtwomLirzut66GhGYMAGk=,tag:yWzlxHUhvYJfP7situz1sg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Clvh3e5YTg0wB8QLhlpjtp/AAvGxdlfUy4OFeVNhgvpoUIaZiXSVrKeEthPHYusmqFT38aGjqbzEDdDa5UAwUyE/yHaXHFBMVlJwymoEWcGfxw9K2p8XEW6KLMtI6sWo+dXdyEDlwWOM11l6VtBMOVuEVtV4u8LKtbr6YLhgcTJwp4RG4jRQYsyx27XyGA3uwprSyDJVRqEm0ZMOHnpZAvBS0XiNewX14Z9sLB8xmmdPRUMar8fEXydUIo/JrBav+mzUGH59fOFY+GcvKA==,iv:1Ek1nLBJ5UBNP3JvLC4ks5LLOKGSIsjnulZQN8TC/us=,tag:qu1MyQP8SIYrvKsX0fZ/Sw==,type:str]
    known_hosts: ENC[AES256_GCM,data:F4Nl9/2oMc6gKR+QOYlpHamg0mEXkhAyhlE7jvDppMelHrKzJSSx+qwdcAa7sFzqES3CshdQhqVZuJSQOvBpY597kcdGXHrWALgkeRQhveGS2Rqkcjq49zokmwq020FqKGvQJPWTeFhLpEh2Qt6o9khOlf55sJTwB8Q7+SMcpiwpjAkiAjdRxOWezt6o0d7eGOXLDo17WQhgpK9NoXuRa/xRKvNIXNTemMxC,iv:kcs4hY80So+AwWwAXX1eNwBddxeKHsxkWnr384ttAzY=,tag:xQaUuz33TFPXsmML/jgCYg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR0NFbDNsUXRBTHFaODJ3
            aUxKZjFkS1liR0EvMVNwdWtDMGZyYTM4T25FCmRqczY3SllYdmVHdGJGemtjZUZ3
            RlgxZWVKbkcyaTkrb0x1Y1RDWXM3bHMKLS0tIGR3ckRMN3dkZTdYQWFDN2JZQVpi
            ZU1RVEJXUUl3N1Vxa3RML3pOTE8yUTgKUcgZsfXUvVOyNfBiUmEktzWOFCq8GqmL
            hDbFDju49k1j7RlArTVEIlhBLABK2VRr8XudaXFeUItlFfJ0IWlptA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T15:51:22Z"
    mac: ENC[AES256_GCM,data:6XG0cUGBjZO/ehqvCPmEZ2CmdxXmrR9x/XWNhgVzxYnn3megUwYciv5UEVE/LaGpm+2AotpPcUPSBU2TXQiMGK7w1kRoZWctlYYyovU+RRKVZSTTEC19axlari2wlDaKKpDy/BXBFPDd/MmeeKdDUpjpLjkajS0Py9Qh8B/6MEg=,iv:w/oTzmyOrzdAqdXJ8NhJ0Mcj9L6hGOiPJIQcig9K2Cc=,tag:vn/BHz28fV/v/iwivk1C1g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
