apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Gu414gqx9eAZ1lQ4MlyEXdoX7rqgkmiQ7AwaogmHW410KXDeiXIQRH1ouNQpSyWGRPqAo1E7hREij5/fxyhR4rRrAUiSqCXzsECgp827tlyrSwSv0ZidnHh66dbrAiWzA7n4ethw7LC16FfkGTl+9ludqHRsyyaTlKIp8V0VSSGE19bPAbQUPm9dKEzMxr358E02y2ttu0SWmbxsdQzvREDcbOsAbv465HT70mjq+YyNsJsMGL2FSvJIDYAaP2mmgi1jvmQVxlEl3xHR7WIeWPljR6IgG090KMrjOsPCRc8CzVR6da9N27xsNMplOipyQz+i3T3RGviw16v8kXz9RY9zvrVZXg6K8pqkszgYPV6anC8ZG39Tre0LXAE0buNe,iv:C/lUgOaU270LVWKxnGrJjnzkBM2vfpI7oLzftVFSh7g=,tag:DEmm/42gZjEyb4uRzLYkmQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:9u98Lix4YfBibNtpLVlgEIyDxt9REm4nNz3xJuQow53yv/KNKUh/yl7LhG5wLsssAZETGrl2xtBvx9Nw4OFlDOo+plKm6UaujOY1dyvSeUH/c29YKG+Ru9jIE2MTtrJarXpcgUEzWLSoATlIZ6RsR9eYTTBwnzBsqeAEJSZl61ZHHw+pjClvprUtds5LUfVLjGilx5vkfT4zyAYY9/W7tTIoLlY1ZdaoO9orD7/liyr/US/hMCttbIUdDS5krgEX97gEnHp75vSrwhJbWA==,iv:StKkUJffBb1bEPgFzhUOEZFXdQ886RWi6GntWnlGboc=,tag:bQ6BhyTgToCUU86RtfKrvQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:H2fj6hsOq5VY5fxoU5+vInGeZQbe6eW/nDPBlq/k/LhmzLHhNicP5CVRNmakCVvCgR2LoLaFXTFzb5YIV+tlW+qvvuyVf1WVMQ4OBDCre81x+i8Pwqc4UkOxoUMVwSII4Sq+Plf62SPAZf4dOAqEiQ/+5dC8R8AvEDTLqAZPlqhEWou5m6QLF0JaI6EvZCtp5HFZ/PDiiV/IdGmE3gHMWw/MPU9gIIPB6+D3,iv:R5rSUe4x/LJ7gwLYUPIaMJabmBDi4Pd5o7KnMgjcc4c=,tag:e1iGAtVKjs9K6NvfiFNWtw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVmIzb3FqSFZUeDJHS2RK
            TUdVK2RaNTliVnhkVTVZcytxeCtKdVFWL1g4CkQvZ3BMUzZFb2VIZmRCT3F0SHpT
            ak1KdUVCWUlLeGZQMW9LaUU3WkNoaG8KLS0tIFYwTmFWVHZXUE5Db3MzLzZIWG9B
            OGlJT3lQemRaM09SNGxWSzBkWmdUY0EKQ3bSTt159WdMUAAvs+8sctqpZuGdUqgK
            w9gkb77mmhX6VH+EXPkgxSRk3GHInDnGUa36GstbyjXiijBxzFvdcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-31T16:05:14Z"
    mac: ENC[AES256_GCM,data:bGQwnh7+DfxfrEH4uh0EiCqPhIiCgWmUft5X8rca/KeWio62SEqqbfqiUX10sP1D+sx8ElizY7ZuXgVvyCA+i7+v99pmW7B1SDvFTwsa5i4LJXaskiu4VxvqacPoSF5+/Vh9SM8uaLbULG+DGWg9hNZy3DZaVsxt9aBvutk3yYc=,iv:rcUHlydYiI7bFKzWURfITdlrktbqFgtFPuZVbvBMUNE=,tag:v90Vg+GXToKtQbQrSwMQzA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
