apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gCTD+y07vLIxzVT4tO0Hf9rrfTBsWRZ3rt4V/8zNOHlANeZfxmgDA2wwmUDZN1f4zVwyCpwLk2GF3jOlWKJKZLr1h1xvzk/7eqxwVaDepqG4y4vOfANcdyHdQI4ED617VXZ/XA7YH9MQLF59ZJ2v3zUlx35MffV8dfb/rZ4o6iEE8Rjf/zh/s0t76gaZlYR+di0/Vyx06fSEgCZ25mGpcgl705I8YN/qYQUfAcpmFZ3bMMW/tldaF0gyKA4waus9wMZE+3o/VMdJdadzNWK/F1B5qFWGi6jaeJCUe15L3WKhjYJX6eFDY11vWG117Pfy2RihNiRcSlRoAoIDDl5Jj9Zz3uFpyrFY27sAAiRA8S1qd3kkWkLvcqydUXLBBn59,iv:Vz0Fe4P1YEGXMxL3Aa8QPO7AajHjd0wZNzsMun2RBo0=,tag:4LQ5yI4NrLZZ+PElffcMaQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:xwVci4xmx8IJZvpe6/0CXzWVQlqywI3WzKdE75iczlEC4qiU1WQf3wXLDrBdUl6A/aPdXsdWm0V6oCGWeaCjH1MXte3L/OXQX7EoMcaovZdQqRk+XKaEKIPaU2mnSk2D02lK/diqOXLKyVCKCFVH0J9quSp8Lj4nUk+Ow6nvnau81kzzB5zD/jcUEes8BAjxisZTnGPnEISrVkAhy0zG9xaPT65E3ES8imChda3SqCOCirChlMWFReXKpDjCqI2X8PXpBQC9i/vcCskucA==,iv:evej89VtXNA4jiSqEzvTJqra1r30nXtJ+s/pfplZLFc=,tag:mAxwi7OXanh2yl7doWcHjw==,type:str]
    known_hosts: ENC[AES256_GCM,data:aRPXhNK7PfcunIJI3tE0HJcJUK9CJiwX46t0aCgdWBhp1OV11bBt5EXeU1I3e8N9pzPps6Hbh2XmYjRs1dgsow5qd3zSMwcm9R2gaKZowH8p8yiVA7tXbZFAtuMmekLWBJCrW8tAvOq2Cy6ivWF9QkE0vLs+e8Zmo7O1QwPDi4qzCsPb6fYZVMM/LDpgRNBpbBmjGMNUbbmKhzGj29z8YnvUlynR0TBPCJjt,iv:fh14wxc08zxYVJIoycGikBZDJbcXfWleEgQidJh8ZWY=,tag:scUd0/f98H8GiiO8nSB2Ww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MlBmejBUUW9jREpkSVZ1
            eDRKOEVCNEhvazZoRWl6UnU0RTRuSHdEZDJNCnZBaGdFSVBPcVhuRmJ4bzQySFow
            b01MS3N3aU16MUNnb2g1ZFZTR29qeHcKLS0tIGFMdXRleDdMaU5qb0VzOVhjbHNR
            YVNXVVFlWWtrZmljVk8xNjBPTFAyK0UKuKbydDgPvUrEvYYfKZthnqPNskEwGx8e
            hMJ3VfHZgYf+buO/FXiW93eeAemAG+vdU5MuNMo8zsPhTBsQx7Rczg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T15:27:54Z"
    mac: ENC[AES256_GCM,data:/kitVp9p5qa7iEWbSQ/jUoxZXZcdoWop5RP4gE3KBRcacdUWd4xyjtP3+2OQWJWkwXcNwsTOX8MiRJI2s2bIPb9rr3WXmp2GbtMjP8+RFlizH549DVRZesIrs8r6r57LMejRUB3cHUrYpZW1Sha5s6R9JxfpIwzGbLRtJIh3kc8=,iv:bok+fVQdd7tZCSGoAOHdQWLYdV9lT4OJrEEaKxxPBOk=,tag:O+sIHSyGN2jNrTyvwkP4Ng==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
