apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vDPigw8np8hvqnz7T47W8/XmSQD9Hq7rZkNVY9+nGsVmenbbH8FxgsfyFTZlKmn0qudZPFNRBJA/xxMNP1JrRglXdSh57t5BeIaKC1upOA99odTMggBbPSIhBZlhNcpFqfkQsbhDJmKjBWE1qO6BFOo8sWHbLXIy+vjVilLpDW7pqA+H0HeM04kWGxuc1wpQg0qlRSMiUuiDUu2yAPpHajCAcVNvJfZ33EnVz3QEFcYbi+OLNe1EnmQ0gs7ipL8+i1/lMwnCfBnoNCHaHrR/PsN3IicY8vVjHOUrptdKib0i7MsQntlxpZAFyX6+m6B5RNNo3jsF+prxZNwq/qQ0qj62GoGz7WWii5N/8WsGVyI9AZ8EATgsxcuUVZsHmlEf,iv:r8xGTcubooDxxAUDMnzwQ7FOobMfLrTouSQ94cyc8g8=,tag:Ap+wavVL2y8E0d1T7I7Pfw==,type:str]
    identity.pub: ENC[AES256_GCM,data:k0b0ezBFpoT0VSnAEIM1KBJWkMsg043WJQ9IdXFJtwUOEa2DKsZEc+kGhP+j0fmqBPCZBJuwO3nVOBX71DwEyPNRSVVb00uXyFImN1X9lweCeR8QgZ2NVZApmDZL0YBc7YCeXtF6bC6Kn3Bzn+0knWY/ohFCgPhCinQQBreXHI1IT8+Yva7PWauG7w4KCKRpoxhqLcE8sodn3cs188rgBLSobs8wK12ob2EWYRhBn9iC0RO9ApMKY402fKZJKK72yBGLb2mAQFl8vyXumQ==,iv:pnvajZDQnQBIm6CbT8JIezuolQd6Lu0cNvWNjkTcalo=,tag:jk4KZ3CPJ+obhdF+bqzgfw==,type:str]
    known_hosts: ENC[AES256_GCM,data:M+PLrRdZ1Ondc0Arn4It+P+rDeOMEMmeiURqiLI23Sf44MFq38G44ItXBgtzyU4ANugo9+nG1L9EIsEUOGxLqrffC0PUcR7eCGsrKu1Ez05bP/Ae3nvPnydcPyfGV/nwj6GCphAA/mC4iQIqGlEdTvvClGMRmIT3rjBUq/DkPWhUt1Xagn+00FmC7xb22G68r46RgtsKFI9DfOsEUvKKgPaRIVs1LGN6FCtz,iv:ZOZd7pfP5CUZCPc6caQiqxnQMBXL+D6Z9SADW36P5EM=,tag:bI2QW/+/bbRbMe+irwyiuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdnRVb1djS0R3R3JaSVlP
            YUxDVFkydFhUL25pTGJxd1ZQZU5qOXI2N3hRCjFuUW45clRrUTJFZHFoMEhDSy8z
            Y256T0FJZEdvLzJjOXZjbTdweVJoYUUKLS0tIEo3bU9kc0l5YTYrZ3lpajhtRWpJ
            YmZmakhDZksrYklMMWx0SlRWVWJUbWcKXwor5WMP4nc6DE9ii7E3tTP2Z8mdzG35
            noaiGqDLviKbkWZxrUla/qBYa4koMxNEXkVrhje4mfuwtZOgJPU0Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-13T12:30:30Z"
    mac: ENC[AES256_GCM,data:s8HWNwjP3BUolAYArxQpFFb1TXYOcf+3xv94F59ca4mQgnlWGeUjBcd/RqporQTpakuu816X0znAxau/hJ4tJl+wjiCvXT7oFBf91WUoXfK3+iFlYTqUgYFtOGyV8cDBBCFe37MbDs2U7XpmWYDWDM1cet1yPZ3PpuiTMsqDl3k=,iv:PRz0Pd+V3LRyfb89pa9Sm3oyR/b4MJsfooTV7Bd3ICA=,tag:HScjrX2k5l6Cq89rd2PIuQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
