apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:k1T/OAi1VRJ7GYlDPxXsrNEUc3H2MYrMoANMyNNkt9zjXNeheiqRTdUXsGzrtlVCYAlRhWD/Xl2mI64frQAJX3Q3NoKvM7ISz3miiWJ22eWNmvf4uqJCPGVxAv9nH+62BHPzowINoXUZnXqRJDyvIojZdjvdNWeBw38Iyba1jKIPiA2xnRXsHIaVXMXWYhh6HrB+k6vQ5kyX2gvpV7x9KvVtSLRDDFzwA2jWBGtmBd+Mg1vcQL1xEhupQlONp/3BDluZ/x6D/9JGnZEN3hlWifK3uArQllrH1h4ZnsIrnlg/8Jz9IKbXpXAf6xDleNA3JzMidzOJJVrLmLm4loVwEBG/1ph/v+K62g0LWJ4fauvNbIHE4WjqGu7OwS2IZ/Ph,iv:eIa6wz4XA64Fbs3RNUmEH49pGaLb1jtfhWUUokRp4Ho=,tag:OJAooWzin+LgQitHBaaHXQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:SuZrZUFPs9u8es1wN/ad4fOM2KQvYm6Y52sg2n8NtFh7ykNPW+wobVuVFE+Tcl3xRNHqoUmTXsa+FiP9otKWoAxwiUUe4WyL0ukkyAEwPOF2xBoOJS9MKxxFVqRQUkBNFtkwrwbPtJMxQKMWoAoNYnfQrHckW1MDC8VU2M3hfn2Bhd4urHYTqMWy6L/PtAa5QAl/ncUN4W3BwTPrvPmZh9qAkd3wprFUmqo37H71mQmBWobAQj0CmOky48wk/vc0uWw/QzfJt/0+BpEKjQ==,iv:6qoBhy9C/xaeHOQ4EUa9HHl3Oqkl7dQbK303dgWj+O4=,tag:TxMY2R67M56MCkN6gm5iIg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ECkpsko42t3b/U34ATjKlegtr0ml97xTDQMb0Q0jmXdQiweriZdCc885b2TZiT1WmyT7ANSwsePMtaR5oadgU190dixWmfd+umStZTisUG9tiO20E8VCdN3bJZqIqSIcrWwk6278tYZNRnaTYcKaEAOzHzDWyvjMmov+ZUyujjEz0zH5JiQRiD639auh0HCqFqSfSpo65gXX9Vvjphg0VUCcD+NAoHL0Wl0f,iv:atFyys9w94OHDJod2I/QhsiVDk2aRcvJk281N/8isGs=,tag:e9E1GEDb7WpV6HsYfbMRIw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeWp3Z2NMYTRudE4wM015
            NWloaElnSGZaU0FRZzBtZ1U4REV2VG5sMUF3ClNvOG41RFNWN0ZUSUxITXgzYTNH
            dGxlOHhlWUtVUTVxZllEMXc5S0dkTzgKLS0tIDZHV0xVc25qQmkvZG4rL3pBVjE3
            empEWXVtcEhwcmYrUytacFdVQno0UGcKt2vHtBL7ddhO7b4vy4VG+xWNz6DOMYle
            RSN5L+NWhaJ0hv8M+vaRTPaWsLBZ+P8KhbMDaXyIqqqPWyZJH/I7KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-31T18:22:30Z"
    mac: ENC[AES256_GCM,data:WdHhq3KUvH4I55j+qnqAlFMHVpUDYViG4MD05M63k3yOiXp0XzoNXAp1m9FegLo9wgZ7GCzRZVdvCe6MeBpB4V1iRzq054AVFeCak/KypSp3c/gxReIfBwzWVNZwaUXdaI6sinqM5+UuG+/mTQP7rpC1GvzRSx+8S7oJmkzy+98=,iv:LvzA6YEhLp/v6Oh3wOGMGkUjTGZUl03r0eAhXqNKea8=,tag:uqb5Sh6cNfBar2YED+Tv1w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
