apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Td+RyXF8UgUcacnULJE5RSLZYA/KFFWJYfHexnC3udUXWZlqQcyDbBUQ1C623VkNaxWEPtiKKKfil9GkHoYEvQDSzMKa1S0QU6GD7fIv/VAjHTyDT7kv+6Nzpn4Ysmx4gCmigXQn0PSoIrWVBdJdtHIZh7ywYBIb8QiTQKNwRhsilo2sAYw7jJQSt8+Up78O/G6WKzp7IkwW10f2PF0vjfY7NVJ3yELXQNJXrJ0myLKyrNPmQKRGDsEodsExrAkb9aa1AqI1/ZuL0rihAKj4jvlEy+1Cf2Wbff230zjFFfUWBB+fzJBWgS602vSOtV0owZbkIcideMlRdCd55aS0QKWvtOgOnzCNDeWTOBebX0qwHy9bcAk0wcyL5P97ZzRT,iv:Ruoxg4nkgclRhut+6JttEBV4LLnTV9WxaVWPV79vMAE=,tag:DaJIZ7EKbcErtTdlwNqiFQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:FNNPYOMaDOHefZwz0AZQAPKKNNhcnLTx1KijB7qbRNR9OtUXz+cPfvc7YdmfIhdlhqGF16jK1BRRGikdIc7qJcMvQfynooXMx1XAECVL6x7GT5gkOeD21dh/0DROwuMfROJ7TJEkoHYz07CgRyCseo1kG7cTZRSrqRGlLH2QVpW9E3mCMr5X23AYujUFjvDeciLcj75QYLaSTCKaiD9d/yjfsW/kO3ysfO6+tcr+yl4aBGfmwXh1fRsTIBwnpoxHLiV+4c2A8JfX1sHTAg==,iv:z06x3Ww76DO1ypBdZL2HT9JCo4QGfK3/yA9c0mBHlxg=,tag:xW6jndTGfrrc0NDmuppNzA==,type:str]
    known_hosts: ENC[AES256_GCM,data:fpXly6NNTmKBWpB1s/j+FezG44ypqwhzPQrQ5JZcw8+xiu4dgFzzJkAS9hCqNoZRGwY8awoMO8fxqoEBIrrulTEuPpP7p0bJheUR7L+HCN9KUj01wcGAqyDhjwPVy3Yoqqe8NEj69RCNW2YKLgue9qQO90sA25SXDC5061jMTBqoYkwmGhLbM9yuGizSW5CnEawL7Ou0eSRS7xL2H3dvtgkzlgho8mIKtojt,iv:/JnGw2IhzkrV9zMn8Dvn1idbRV4z1d2zT/mT1B3avNo=,tag:png+kuywxkWtm2G6y+donw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rznlpav2n5ph2wmyzjlhc4t44cu5fcutm06z0764745e3j64xc2qcayjez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVWVkK0phL0lSYmoxRkt1
            MktmUkllQzNoRjhCSldoRDYwdUFVaGlwS1JrCmZFOHFla1Y1ZU1lMEVTU1g4M2Iz
            OEdVOGpqOFFyTkpVRHAreFVid3pHbTQKLS0tIEZNNTlhTnJkcDV4OFdFaUZxdGNx
            MzBCZC9ySEc2TGc0d2I4QWk3NndKZ2sKo74Be+3ujJ7Wla6Y4tThUlQveg+Cbv/h
            trba+D2c2mWlI6bTLNFG+vwaOx+HvKzY76iplyzieGe4UHqM7KriEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T08:00:06Z"
    mac: ENC[AES256_GCM,data:s+SOCkBsWdOgxnd5AyFgxF3+d7Gn6ZaLxUd334jDw2RBR+sgmZBF0Pm0CrN33bwuMfHVjsmho+KLVSW5jP/yiHo1oDHZ08XGD60ps5uyIwJWmqFuckNMtlGUaB1Zw2oV13mZYYmk50ikJ4jd4+dw3k3xDYInuvViMThT7K6I1QE=,iv:D9j5gi8KRVrgBteHfLk13gX46wmQKrA07NJlmCbF6Qs=,tag:VoxgY8kZEfAaFDVDbV6YWA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
