apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 8.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: homepage
  values:
    TZ: Europe/Prague
    credentials:
      backup:
        name: backup
        type: s3
        url: ${BACKUP_S3_URL}
        bucket: ${BACKUP_S3_BUCKET}
        accessKey: ${BACKUP_S3_ACCESS_KEY}
        secretKey: ${BACKUP_S3_SECRET_KEY}
        encrKey: ${BACKUP_S3_ENCRYPTION_KEY}
    persistence:
      config:
        enabled: true
        mountPath: /app/config
        volsync:
          - credentials: backup
            dest:
              enabled: true
            name: config
            src:
              enabled: true
            type: restic
    ingress:
      main:
        enabled: true
        hosts:
          - host: ${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: auth
                namespace: traefik
