apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/democratic-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
