---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: flaresolverr
spec:
  interval: 15m
  chart:
    spec:
      chart: flaresolverr
      version: 15.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  values:
    credentials:
      backup:
        name: backup
        type: s3
        url: ${BACKUP_S3_URL}
        bucket: ${BACKUP_S3_BUCKET}
        accessKey: ${BACKUP_S3_ACCESS_KEY}
        secretKey: ${BACKUP_S3_SECRET_KEY}
        encrKey: ${BACKUP_S3_ENCRYPTION_KEY}
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backup
            dest:
              enabled: true
            src:
              enabled: true
