---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.4.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    defaultCertificate: "domain-0-wildcard"
    workload:
      main:
        replicas: 1
        strategy: RollingUpdate
    metrics:
      main:
        enabled: false
    service:
      main:
        type: ClusterIP
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          web:
            enabled: true
            port: 80
            protocol: http
            redirectTo: websecure
            forwardedHeaders:
              enabled: true
              # -- List of trusted IP and CIDR references
              trustedIPs:
                - 173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
                - 172.16.0.0/16
                - 172.17.0.0/16
              # -- Trust all forwarded headers
              insecureMode: false
            # -- Configure (Proxy Protocol Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol] Support
            proxyProtocol:
              enabled: true
              # -- Only IPs in trustedIPs will lead to remote client address replacement
              trustedIPs:
                - 173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
                - 172.16.0.0/16
                - 172.17.0.0/16
              # -- Trust every incoming connection
              insecureMode: false
          websecure:
            enabled: true
            port: 443
            protocol: https
            # -- Configure (Forwarded Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers] Support
            forwardedHeaders:
              enabled: true
              # -- List of trusted IP and CIDR references
              trustedIPs:
                - 173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
                - 172.16.0.0/16
                - 172.17.0.0/16
              # -- Trust all forwarded headers
              insecureMode: false
            # -- Configure (Proxy Protocol Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol] Support
            proxyProtocol:
              enabled: true
              # -- Only IPs in trustedIPs will lead to remote client address replacement
              trustedIPs:
                - 173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
                - 172.16.0.0/16
                - 172.17.0.0/16
              # -- Trust every incoming connection
              insecureMode: false
    middlewares:
      realIP:
        - name: real-ip
          excludedNetworks:
            - 172.16.0.0/16
            - 172.17.0.0/16
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: traefik-regex
                namespace: traefik
              - name: auth
                namespace: traefik
            fixedMiddlewares:
              - name: chain-basic
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: traefik.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
