apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  interval: 15m
  chart:
    spec:
      chart: prowlarr
      version: 17.1.7
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: prowlarr
  values:
    credentials:
      backup:
        name: backup
        type: s3
        url: ${BACKUP_S3_URL}
        bucket: ${BACKUP_S3_BUCKET}
        accessKey: ${BACKUP_S3_ACCESS_KEY}
        secretKey: ${BACKUP_S3_SECRET_KEY}
        encrKey: ${BACKUP_S3_ENCRYPTION_KEY}
    ingress:
      main:
        enabled: true
        hosts:
          - host: prowlarr.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: home
                namespace: traefik
    persistence:
      config:
        enabled: true
        volsync:
          - name: config
            type: restic
            credentials: backup
            dest:
              enabled: false
            src:
              enabled: true
