---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - qbittorrent/ks.yaml
  - flaresolverr/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - sonarr/ks.yaml
  - readarr/ks.yaml
  - bazarr/ks.yaml
